version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - conf/.env
    network_mode: host