"""init migration

Revision ID: 59be72ab5f80
Revises: 
Create Date: 2025-02-26 00:29:13.360711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59be72ab5f80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=320), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=False),
    sa.Column('wind_gust', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=False),
    sa.Column('rain', sa.String(length=320), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_city'), 'queries', ['city'], unique=False)
    op.create_index(op.f('ix_queries_description'), 'queries', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_description'), table_name='queries')
    op.drop_index(op.f('ix_queries_city'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
